### ISSUE TITLE
issue while trying to install lib

### ISSUE THREAD

**Issue by 0xaaiden** [BobTheBuidler/ypricemagic#469] opened 2023-11-26 04:08 UTC
pip3 install ypricemagic yields an error on new pip versions

```
Collecting pyyaml==5.4.1 (from eth-brownie<1.20,>=1.19.3->ypricemagic)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
[5]
0s

```

**Comment by BobTheBuidler** [comment] 2024-02-17 04:19
another user reported this same issue on eth-portfolio. He identified a fix you can see here https://github.com/BobTheBuidler/eth-portfolio/issues/30#issuecomment-1902071034

The issue is external to ypricemagic so I'll go ahead and close this. Thank you for reporting.

**Closed by BobTheBuidler** 2024-02-17 04:19 UTC
